# Generated by Django 4.2.23 on 2025-06-26 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AgeGroups",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("label", models.CharField(max_length=255)),
                ("min_age", models.PositiveIntegerField(blank=True, null=True)),
                ("max_age", models.PositiveIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "age_groups",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="AvailabilityDayCourts",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                "db_table": "availability_day_courts",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="AvailabilityDayDurations",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("duration", models.PositiveSmallIntegerField()),
            ],
            options={
                "db_table": "availability_day_durations",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="AvailabilityDayIntervals",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("interval_number", models.PositiveIntegerField()),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                (
                    "discount_percent",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "availability_day_intervals",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="AvailabilityDays",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("day", models.CharField(max_length=9)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "availability_days",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Cache",
            fields=[
                (
                    "key",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("value", models.TextField()),
                ("expiration", models.IntegerField()),
            ],
            options={
                "db_table": "cache",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="CacheLocks",
            fields=[
                (
                    "key",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("owner", models.CharField(max_length=255)),
                ("expiration", models.IntegerField()),
            ],
            options={
                "db_table": "cache_locks",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="ClubBannerImages",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("banner_img", models.CharField(max_length=255)),
                (
                    "banner_img_cropped",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("is_primary", models.IntegerField()),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "club_banner_images",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="ClubCheckInSettings",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("type", models.CharField(max_length=10)),
                ("open_ms_before", models.IntegerField()),
                ("close_ms_after", models.IntegerField()),
                ("default_active", models.IntegerField()),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "club_check_in_settings",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="ClubLevelSystems",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "club_level_systems",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="ClubOpeningHours",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("day", models.CharField(max_length=9)),
                ("is_closed", models.IntegerField()),
                ("opening_time", models.TimeField(blank=True, null=True)),
                ("closing_time", models.TimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "club_opening_hours",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Clubs",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=64)),
                ("short_name", models.CharField(blank=True, max_length=32, null=True)),
                (
                    "organisation_name",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "organisation_no",
                    models.CharField(blank=True, max_length=16, null=True),
                ),
                ("is_parent_club", models.IntegerField()),
                ("no_of_branches", models.IntegerField()),
                ("about_the_hall", models.TextField(blank=True, null=True)),
                ("timezone", models.CharField(blank=True, max_length=64, null=True)),
                (
                    "contact_email",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                ("telephone", models.CharField(blank=True, max_length=16, null=True)),
                ("facebook", models.CharField(blank=True, max_length=255, null=True)),
                ("twitter", models.CharField(blank=True, max_length=255, null=True)),
                ("address", models.CharField(blank=True, max_length=255, null=True)),
                ("postal_code", models.CharField(blank=True, max_length=10, null=True)),
                ("website", models.CharField(blank=True, max_length=255, null=True)),
                ("logo_url", models.CharField(blank=True, max_length=255, null=True)),
                ("no_of_followers", models.IntegerField()),
                (
                    "location_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=10, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=11, null=True
                    ),
                ),
                ("city", models.CharField(blank=True, max_length=255, null=True)),
                ("state", models.CharField(blank=True, max_length=255, null=True)),
                ("country", models.CharField(blank=True, max_length=255, null=True)),
                ("status", models.CharField(max_length=26)),
                ("reason", models.TextField(blank=True, null=True)),
                ("is_admin", models.IntegerField()),
                ("cafe_restaurant", models.IntegerField()),
                ("conference_rooms", models.IntegerField()),
                ("dressing_room", models.IntegerField()),
                ("free_parking", models.IntegerField()),
                ("handicapped", models.IntegerField()),
                ("rental", models.IntegerField()),
                ("shop", models.IntegerField()),
                ("allow_child_credits", models.IntegerField()),
                ("allow_membership", models.IntegerField()),
                ("allow_player_matches", models.IntegerField()),
                ("accepts_freelance_coaches", models.IntegerField()),
                ("default_cancellation_time_booking", models.BigIntegerField()),
                ("default_future_booking_days", models.IntegerField()),
                ("indoor_courts", models.IntegerField()),
                ("indoor_courts_status", models.IntegerField()),
                ("outdoor_courts", models.IntegerField()),
                ("outdoor_courts_status", models.IntegerField()),
                ("single_courts", models.IntegerField()),
                ("single_courts_status", models.IntegerField()),
                ("double_courts", models.IntegerField()),
                ("double_courts_status", models.IntegerField()),
                (
                    "waiver_notice",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("require_waiver_acceptance", models.IntegerField()),
                ("profile_submission_deadline_hours", models.IntegerField()),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "clubs",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="ClubsAdditionalInformation",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("feature_name", models.CharField(max_length=255)),
                ("is_available", models.IntegerField()),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "clubs_additional_information",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="ClubSports",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("membership_fee", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "club_sports",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="CoachActivityContents",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("type", models.CharField(max_length=5)),
                ("file_url", models.CharField(max_length=255)),
                ("file_extension", models.CharField(max_length=10)),
                (
                    "thumbnail_url",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "coach_activity_contents",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Coaches",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "home_address",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "emergency_contact",
                    models.CharField(blank=True, max_length=16, null=True),
                ),
                (
                    "emergency_contact_person_name",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "emergency_contact_person_relationship",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "banner_image",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("bio", models.TextField(blank=True, null=True)),
                ("serving_role", models.CharField(max_length=13)),
                ("training_type", models.CharField(max_length=7)),
                ("job_type", models.CharField(max_length=9)),
                ("can_instruct", models.IntegerField()),
                ("experience_min", models.PositiveIntegerField(blank=True, null=True)),
                ("experience_max", models.PositiveIntegerField(blank=True, null=True)),
                ("is_hidden", models.IntegerField()),
                ("can_cancel_sessions", models.IntegerField()),
                ("default_cancel_time", models.IntegerField()),
                ("booking_days_ahead", models.IntegerField()),
                ("min_hours_before_booking", models.IntegerField()),
                ("is_verified", models.IntegerField()),
                ("status", models.CharField(max_length=18)),
                ("reason", models.CharField(blank=True, max_length=255, null=True)),
                ("ratings", models.DecimalField(decimal_places=1, max_digits=3)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "coaches",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="CourtBookingBanners",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "banner_image",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "court_booking_banners",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="CourtBookingCourts",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "court_booking_courts",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="CourtBookingDescriptions",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "court_booking_descriptions",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="CourtBookings",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255)),
                ("activity_type", models.CharField(max_length=10)),
                ("cancellation_period", models.IntegerField(blank=True, null=True)),
                ("check_in_opens_before_hours", models.IntegerField()),
                ("check_in_closes_after_hours", models.IntegerField()),
                (
                    "discount_codes_applied",
                    models.TextField(blank=True, db_collation="utf8mb4_bin", null=True),
                ),
                ("booking_date", models.DateField()),
                ("booking_day", models.CharField(max_length=9)),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("rule", models.TextField(blank=True, null=True)),
                ("repeat_every", models.IntegerField()),
                ("is_recurring", models.IntegerField()),
                ("recurrence_order", models.IntegerField()),
                (
                    "customize_recurrent_activity_end_datetime",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("info", models.TextField(blank=True, null=True)),
                ("is_group_booking", models.IntegerField()),
                ("group_id", models.PositiveBigIntegerField(blank=True, null=True)),
                (
                    "withdrawal_lock_hours",
                    models.PositiveBigIntegerField(
                        blank=True,
                        db_comment="Number of hours before event start when withdrawal is locked",
                        null=True,
                    ),
                ),
                ("category", models.CharField(max_length=17)),
                ("tournament_format", models.CharField(max_length=14)),
                ("type", models.CharField(max_length=7)),
                ("class_level", models.CharField(blank=True, max_length=12, null=True)),
                ("is_multi_court_booking", models.IntegerField()),
                ("is_checked_terms_and_conditions", models.IntegerField()),
                ("total_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("discount", models.IntegerField(blank=True, null=True)),
                (
                    "price_per_person",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("payment_status", models.CharField(max_length=7)),
                (
                    "payment_method",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("require_player_level", models.IntegerField()),
                ("automatic_cancellation", models.IntegerField()),
                ("auto_cancel_if_dhc", models.IntegerField()),
                ("auto_cancel_if_dpnr", models.IntegerField()),
                ("get_feedback", models.IntegerField()),
                ("hide_training_from_app", models.IntegerField()),
                ("participant_limit", models.IntegerField(blank=True, null=True)),
                ("no_of_points", models.IntegerField(blank=True, null=True)),
                ("is_private_tournament", models.IntegerField()),
                ("open", models.IntegerField(blank=True, null=True)),
                ("booking_status", models.CharField(max_length=9)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "court_bookings",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="CourtBookingTemplates",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("type", models.CharField(max_length=255)),
                ("details", models.TextField()),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "court_booking_templates",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Courts",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("surface", models.CharField(blank=True, max_length=64, null=True)),
                ("color", models.CharField(blank=True, max_length=32, null=True)),
                ("image", models.CharField(blank=True, max_length=255, null=True)),
                ("status", models.CharField(max_length=8)),
                ("court_location_type", models.CharField(max_length=7)),
                ("court_type", models.CharField(max_length=6)),
                ("visibility", models.CharField(max_length=11)),
                ("note", models.TextField(blank=True, null=True)),
                ("buffer_time_between_slots", models.IntegerField()),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "courts",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="CourtSlotDurations",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("duration", models.IntegerField()),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "court_slot_durations",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Currencies",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255)),
                ("code", models.CharField(max_length=3, unique=True)),
                ("symbol_left", models.CharField(blank=True, max_length=5, null=True)),
                ("symbol_right", models.CharField(blank=True, max_length=5, null=True)),
                ("decimal_place", models.IntegerField()),
                ("value", models.DecimalField(decimal_places=6, max_digits=15)),
                ("status", models.IntegerField()),
                ("is_default", models.IntegerField()),
                ("date_modified", models.DateTimeField()),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "currencies",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="FailedJobs",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("uuid", models.CharField(max_length=255, unique=True)),
                ("connection", models.TextField()),
                ("queue", models.TextField()),
                ("payload", models.TextField()),
                ("exception", models.TextField()),
                ("failed_at", models.DateTimeField()),
            ],
            options={
                "db_table": "failed_jobs",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="GroupCategories",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255, unique=True)),
                ("slug", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("is_active", models.IntegerField()),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "group_categories",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Groups",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("information", models.TextField(blank=True, null=True)),
                ("image", models.CharField(blank=True, max_length=255, null=True)),
                ("max_members", models.PositiveIntegerField(blank=True, null=True)),
                ("gender_restriction", models.CharField(max_length=6)),
                ("timezone", models.CharField(blank=True, max_length=255, null=True)),
                ("visibility", models.CharField(max_length=7)),
                ("hidden_in_feeds", models.IntegerField()),
                ("is_approval_required", models.IntegerField()),
                ("status", models.CharField(max_length=8)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "groups",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="JobBatches",
            fields=[
                (
                    "id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=255)),
                ("total_jobs", models.IntegerField()),
                ("pending_jobs", models.IntegerField()),
                ("failed_jobs", models.IntegerField()),
                ("failed_job_ids", models.TextField()),
                ("options", models.TextField(blank=True, null=True)),
                ("cancelled_at", models.IntegerField(blank=True, null=True)),
                ("created_at", models.IntegerField()),
                ("finished_at", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "job_batches",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Jobs",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("queue", models.CharField(max_length=255)),
                ("payload", models.TextField()),
                ("attempts", models.PositiveIntegerField()),
                ("reserved_at", models.PositiveIntegerField(blank=True, null=True)),
                ("available_at", models.PositiveIntegerField()),
                ("created_at", models.PositiveIntegerField()),
            ],
            options={
                "db_table": "jobs",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Levels",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255, unique=True)),
                (
                    "value",
                    models.DecimalField(decimal_places=2, max_digits=10, unique=True),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "levels",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Migrations",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("migration", models.CharField(max_length=255)),
                ("batch", models.IntegerField()),
            ],
            options={
                "db_table": "migrations",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="OauthAccessTokens",
            fields=[
                (
                    "id",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("user_id", models.PositiveBigIntegerField(blank=True, null=True)),
                ("client_id", models.CharField(max_length=36)),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("scopes", models.TextField(blank=True, null=True)),
                ("revoked", models.IntegerField()),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "oauth_access_tokens",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="OauthAuthCodes",
            fields=[
                (
                    "id",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("user_id", models.PositiveBigIntegerField()),
                ("client_id", models.CharField(max_length=36)),
                ("scopes", models.TextField(blank=True, null=True)),
                ("revoked", models.IntegerField()),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "oauth_auth_codes",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="OauthClients",
            fields=[
                (
                    "id",
                    models.CharField(max_length=36, primary_key=True, serialize=False),
                ),
                ("user_id", models.PositiveBigIntegerField(blank=True, null=True)),
                ("name", models.CharField(max_length=255)),
                ("secret", models.CharField(blank=True, max_length=100, null=True)),
                ("provider", models.CharField(blank=True, max_length=255, null=True)),
                ("redirect", models.TextField()),
                ("personal_access_client", models.IntegerField()),
                ("password_client", models.IntegerField()),
                ("revoked", models.IntegerField()),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "oauth_clients",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="OauthPersonalAccessClients",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("client_id", models.CharField(max_length=36)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "oauth_personal_access_clients",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="OauthRefreshTokens",
            fields=[
                (
                    "id",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("access_token_id", models.CharField(max_length=100)),
                ("revoked", models.IntegerField()),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "oauth_refresh_tokens",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Permissions",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("guard_name", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "permissions",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Players",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("status", models.CharField(max_length=8)),
                ("is_premium", models.IntegerField()),
                ("blood_type", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "emergency_contact_person_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "emergency_contact",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "emergency_contact_person_relationship",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("facebook", models.CharField(blank=True, max_length=255, null=True)),
                ("twitter", models.CharField(blank=True, max_length=255, null=True)),
                ("address", models.TextField(blank=True, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "players",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="PlayerSportLevels",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("rating", models.TextField()),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "player_sport_levels",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="QuestionnaireResponses",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("answer", models.TextField()),
                ("answer_description", models.TextField(blank=True, null=True)),
                ("rating", models.FloatField()),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "questionnaire_responses",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Questionnaires",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("question", models.TextField()),
                ("question_for_db", models.TextField()),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "questionnaires",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Roles",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("guard_name", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "roles",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Specialties",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=64, unique=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "specialties",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Sports",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("icon", models.CharField(blank=True, max_length=255, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "sports",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="UserAvailabilities",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("type", models.CharField(max_length=8)),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
                ("valid_from", models.DateTimeField(blank=True, null=True)),
                ("valid_until", models.DateTimeField(blank=True, null=True)),
                ("is_default", models.IntegerField()),
                ("is_active", models.IntegerField()),
                ("priority", models.PositiveIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "user_availabilities",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="UserAvailabilityDayDurationPrices",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("min_players", models.PositiveIntegerField()),
                ("max_players", models.PositiveIntegerField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=8)),
            ],
            options={
                "db_table": "user_availability_day_duration_prices",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Users",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("user_name", models.CharField(max_length=20, unique=True)),
                ("uuu_id", models.CharField(max_length=255, unique=True)),
                ("email", models.CharField(max_length=96, unique=True)),
                ("first_name", models.CharField(blank=True, max_length=32, null=True)),
                ("last_name", models.CharField(blank=True, max_length=32, null=True)),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=16, null=True, unique=True),
                ),
                ("gender", models.CharField(max_length=6)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("image", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=10, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=11, null=True
                    ),
                ),
                ("city", models.CharField(blank=True, max_length=255, null=True)),
                ("state", models.CharField(blank=True, max_length=255, null=True)),
                ("country", models.CharField(blank=True, max_length=255, null=True)),
                ("user_type", models.CharField(max_length=17)),
                ("user_type_id", models.PositiveBigIntegerField(blank=True, null=True)),
                ("password", models.CharField(max_length=255)),
                (
                    "old_password",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("code", models.CharField(blank=True, max_length=40, null=True)),
                ("ip", models.CharField(blank=True, max_length=40, null=True)),
                ("provider", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "provider_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("otp", models.CharField(blank=True, max_length=255, null=True)),
                ("otp_expires_at", models.DateTimeField(blank=True, null=True)),
                ("otp_used_at", models.DateTimeField(blank=True, null=True)),
                ("otp_attempts", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "users",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="UserSpecialties",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                "db_table": "user_specialties",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="UserSports",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                "db_table": "user_sports",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="CategoryGroup",
            fields=[
                (
                    "group_category",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        primary_key=True,
                        serialize=False,
                        to="laravel_models.groupcategories",
                    ),
                ),
            ],
            options={
                "db_table": "category_group",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="ModelHasPermissions",
            fields=[
                (
                    "permission",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        primary_key=True,
                        serialize=False,
                        to="laravel_models.permissions",
                    ),
                ),
                ("model_type", models.CharField(max_length=255)),
                ("model_id", models.PositiveBigIntegerField()),
            ],
            options={
                "db_table": "model_has_permissions",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="ModelHasRoles",
            fields=[
                (
                    "role",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        primary_key=True,
                        serialize=False,
                        to="laravel_models.roles",
                    ),
                ),
                ("model_type", models.CharField(max_length=255)),
                ("model_id", models.PositiveBigIntegerField()),
            ],
            options={
                "db_table": "model_has_roles",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="RoleHasPermissions",
            fields=[
                (
                    "permission",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        primary_key=True,
                        serialize=False,
                        to="laravel_models.permissions",
                    ),
                ),
            ],
            options={
                "db_table": "role_has_permissions",
                "managed": False,
            },
        ),
    ]
