# Generated by Django 4.2.23 on 2025-07-17 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("laravel_models", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Community",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("sport", models.CharField(max_length=50)),
                ("level", models.CharField(max_length=50)),
                ("is_private", models.BooleanField(default=False)),
                ("location", models.CharField(blank=True, max_length=255)),
                ("topic", models.CharField(blank=True, max_length=100)),
                ("requires_approval", models.BooleanField(default=False)),
                (
                    "cover_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="community_covers/"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "club",
                    models.ForeignKey(
                        db_column="club_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="laravel_models.clubs",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        db_column="created_by",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="communities_created",
                        to="laravel_models.users",
                    ),
                ),
            ],
            options={
                "db_table": "communities",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CommunityPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="community_posts/"
                    ),
                ),
                (
                    "video",
                    models.FileField(
                        blank=True, null=True, upload_to="community_posts/videos/"
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True, null=True, upload_to="community_documents/"
                    ),
                ),
                ("category", models.CharField(blank=True, max_length=100)),
                ("tags", models.CharField(blank=True, max_length=255)),
                ("is_private", models.BooleanField(default=False)),
                ("location", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="laravel_models.users",
                    ),
                ),
                (
                    "community",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posts",
                        to="chat.community",
                    ),
                ),
            ],
            options={
                "db_table": "community_posts",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MarketplaceItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("image", models.CharField(blank=True, max_length=255, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "marketplace_items",
            },
        ),
        migrations.CreateModel(
            name="CommunityMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(blank=True)),
                (
                    "file",
                    models.FileField(
                        blank=True, null=True, upload_to="chat_files/community/"
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("is_read", models.BooleanField(default=False)),
                (
                    "community",
                    models.ForeignKey(
                        db_column="community_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="chat.community",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        db_column="sender_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="laravel_models.users",
                    ),
                ),
            ],
            options={
                "db_table": "community_messages",
                "ordering": ["timestamp"],
            },
        ),
        migrations.CreateModel(
            name="CommunityMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_admin", models.BooleanField(default=False)),
                ("is_approved", models.BooleanField(default=True)),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                (
                    "community",
                    models.ForeignKey(
                        db_column="community_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="chat.community",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="laravel_models.users",
                    ),
                ),
            ],
            options={
                "db_table": "community_memberships",
            },
        ),
        migrations.CreateModel(
            name="CommunityFavorite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("favorited_at", models.DateTimeField(auto_now_add=True)),
                (
                    "community",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="chat.community"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="laravel_models.users",
                    ),
                ),
            ],
            options={
                "db_table": "community_favorites",
            },
        ),
        migrations.CreateModel(
            name="ActivityMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(blank=True)),
                (
                    "file",
                    models.FileField(
                        blank=True, null=True, upload_to="chat_files/activity/"
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("is_read", models.BooleanField(default=False)),
                (
                    "activity",
                    models.ForeignKey(
                        db_column="activity_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activity_messages",
                        to="laravel_models.courtbookings",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activity_sent_messages",
                        to="laravel_models.users",
                    ),
                ),
            ],
            options={
                "db_table": "activity_messages",
                "ordering": ["timestamp"],
            },
        ),
        migrations.CreateModel(
            name="UserFollower",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "follower",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="following",
                        to="laravel_models.users",
                    ),
                ),
                (
                    "following",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="followers",
                        to="laravel_models.users",
                    ),
                ),
            ],
            options={
                "unique_together": {("follower", "following")},
            },
        ),
        migrations.CreateModel(
            name="PostLike",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("liked_at", models.DateTimeField(auto_now_add=True)),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="likes",
                        to="chat.communitypost",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="laravel_models.users",
                    ),
                ),
            ],
            options={
                "db_table": "post_likes",
                "indexes": [
                    models.Index(fields=["post"], name="post_likes_post_id_c6421f_idx"),
                    models.Index(fields=["user"], name="post_likes_user_id_7d46ab_idx"),
                ],
                "unique_together": {("post", "user")},
            },
        ),
        migrations.CreateModel(
            name="PostComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="chat.communitypost",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="laravel_models.users",
                    ),
                ),
            ],
            options={
                "db_table": "post_comments",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["post"], name="post_commen_post_id_50ec21_idx"
                    ),
                    models.Index(
                        fields=["user"], name="post_commen_user_id_51989a_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="post_commen_created_5d29e6_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(blank=True)),
                (
                    "file",
                    models.FileField(blank=True, null=True, upload_to="chat_files/"),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("is_read", models.BooleanField(default=False)),
                (
                    "receiver",
                    models.ForeignKey(
                        db_column="receiver_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_messages",
                        to="laravel_models.users",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        db_column="sender_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_messages",
                        to="laravel_models.users",
                    ),
                ),
            ],
            options={
                "db_table": "messages",
                "ordering": ["timestamp"],
                "indexes": [
                    models.Index(
                        fields=["timestamp"], name="messages_timesta_ab821b_idx"
                    ),
                    models.Index(fields=["sender"], name="messages_sender__6ae55a_idx"),
                    models.Index(
                        fields=["receiver"], name="messages_receive_432d39_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="MarketplaceMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(blank=True)),
                (
                    "file",
                    models.FileField(
                        blank=True, null=True, upload_to="chat_files/marketplace/"
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("is_read", models.BooleanField(default=False)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="chat.marketplaceitem",
                    ),
                ),
                (
                    "receiver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="marketplace_received_messages",
                        to="laravel_models.users",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="marketplace_sent_messages",
                        to="laravel_models.users",
                    ),
                ),
            ],
            options={
                "db_table": "marketplace_messages",
                "ordering": ["timestamp"],
                "indexes": [
                    models.Index(
                        fields=["timestamp"], name="marketplace_timesta_f58b47_idx"
                    ),
                    models.Index(
                        fields=["item"], name="marketplace_item_id_1058b9_idx"
                    ),
                    models.Index(
                        fields=["sender"], name="marketplace_sender__02e5bd_idx"
                    ),
                    models.Index(
                        fields=["receiver"], name="marketplace_receive_67a3b4_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="CommunityReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reason", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "community",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="chat.community",
                    ),
                ),
                (
                    "reported_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="laravel_models.users",
                    ),
                ),
            ],
            options={
                "db_table": "community_reports",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["community"], name="community_r_communi_e1f004_idx"
                    ),
                    models.Index(
                        fields=["reported_by"], name="community_r_reporte_96c511_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="communitypost",
            index=models.Index(
                fields=["community"], name="community_p_communi_b83422_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="communitypost",
            index=models.Index(
                fields=["author"], name="community_p_author__16beaf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="communitypost",
            index=models.Index(
                fields=["created_at"], name="community_p_created_40799e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="communitypost",
            index=models.Index(
                fields=["category"], name="community_p_categor_22ca67_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="communitypost",
            index=models.Index(
                fields=["is_private"], name="community_p_is_priv_e0eebc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="communitymessage",
            index=models.Index(
                fields=["timestamp"], name="community_m_timesta_1d5668_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="communitymessage",
            index=models.Index(
                fields=["community"], name="community_m_communi_40af48_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="communitymessage",
            index=models.Index(
                fields=["sender"], name="community_m_sender__4b73f7_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="communitymembership",
            unique_together={("community", "user")},
        ),
        migrations.AlterUniqueTogether(
            name="communityfavorite",
            unique_together={("user", "community")},
        ),
        migrations.AddIndex(
            model_name="activitymessage",
            index=models.Index(
                fields=["timestamp"], name="activity_me_timesta_32a396_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="activitymessage",
            index=models.Index(
                fields=["activity"], name="activity_me_activit_51c2a0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="activitymessage",
            index=models.Index(
                fields=["sender"], name="activity_me_sender__f43ccd_idx"
            ),
        ),
    ]
