# Generated by Django 4.2.23 on 2025-06-30 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("laravel_models", "0001_initial"),
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="receiver",
            field=models.ForeignKey(
                db_column="receiver_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="received_messages",
                to="laravel_models.users",
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="sender",
            field=models.ForeignKey(
                db_column="sender_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sent_messages",
                to="laravel_models.users",
            ),
        ),
        migrations.AlterModelTable(
            name="message",
            table="chat_message",
        ),
    ]
