# Generated by Django 4.2.23 on 2025-06-30 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_alter_message_receiver_alter_message_sender_and_more"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="message",
            table=None,
        ),
    ]
