# Generated by Django 4.2.23 on 2025-07-09 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("laravel_models", "0001_initial"),
        ("chat", "0002_marketplaceitem_alter_message_table_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Community",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("sport", models.CharField(max_length=50)),
                ("level", models.CharField(max_length=50)),
                ("is_private", models.BooleanField(default=False)),
                ("location", models.CharField(blank=True, max_length=255)),
                ("topic", models.CharField(blank=True, max_length=100)),
                ("requires_approval", models.BooleanField(default=False)),
                (
                    "cover_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="community_covers/"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "club",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="laravel_models.clubs",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="communities_created",
                        to="laravel_models.users",
                    ),
                ),
            ],
            options={
                "db_table": "communities",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CommunityMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(blank=True)),
                (
                    "file",
                    models.FileField(
                        blank=True, null=True, upload_to="chat_files/community/"
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("is_read", models.BooleanField(default=False)),
                (
                    "community",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="chat.community",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="laravel_models.users",
                    ),
                ),
            ],
            options={
                "db_table": "community_messages",
                "ordering": ["timestamp"],
            },
        ),
        migrations.CreateModel(
            name="CommunityMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_admin", models.BooleanField(default=False)),
                ("is_approved", models.BooleanField(default=True)),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                (
                    "community",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="chat.community",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="laravel_models.users",
                    ),
                ),
            ],
            options={
                "db_table": "community_memberships",
                "unique_together": {("community", "user")},
            },
        ),
    ]
