from django.urls import path
from .views import (
    MessageListCreateView,
    RecentChatsView,
    MarkMessageReadView,
    UnreadCountView,
    ActivityMessageListCreateView,
    MarketplaceItemListCreateView,
    MarketplaceMessageListCreateView,
    CommunityListCreateView,
    CommunityDetailView,
    JoinCommunityView,
    MyCommunitiesView,
    CommunityMembersView,
    CommunityMessageListCreateView,
    CommunityChatThreadsView,
    MyCreatedCommunitiesView,
    ExploreCommunitiesView,
    MyFavoriteCommunitiesView,
    ToggleFavoriteCommunityView,
    MyFollowersView,
    UnfollowUserView,
    MyFollowingView,
    FollowUserView,
    CommunityFeedView,
    PostCommentListCreateView,
    TogglePostLikeView,
    CommunityDocumentsView,
    CommunityPhotosView,
    CommunityVideosView,
    LeaveCommunityView,
    ReportCommunityView,
    AddCommunityMemberView,
)

urlpatterns = [
    # 🔹 Direct Chat (1:1)
    path('messages/', MessageListCreateView.as_view(), name='messages'),
    path('messages/mark-read/', MarkMessageReadView.as_view(), name='mark-message-read'),
    path('messages/unread-count/', UnreadCountView.as_view(), name='unread-message-count'),
    path('recent-chats/', RecentChatsView.as_view(), name='recent-chats'),

    # 🔹 Activity Group Chat
    path('activity/messages/', ActivityMessageListCreateView.as_view(), name='activity-messages'),

    # 🔹 Marketplace Chat
    path('marketplace/items/', MarketplaceItemListCreateView.as_view(), name='marketplace-items'),
    path('marketplace/messages/', MarketplaceMessageListCreateView.as_view(), name='marketplace-messages'),

    # 🔹 Community System
    path('communities/', CommunityListCreateView.as_view(), name='community-list-create'),
    path('communities/<int:id>/', CommunityDetailView.as_view(), name='community-detail'),
    path('communities/<int:community_id>/join/', JoinCommunityView.as_view(), name='join-community'),
    path('communities/my/', MyCommunitiesView.as_view(), name='my-communities'),
    path('communities/<int:community_id>/members/', CommunityMembersView.as_view(), name='community-members'),
    path('communities/<int:community_id>/messages/', CommunityMessageListCreateView.as_view(), name='community-messages'),
    path('communities/chat-threads/', CommunityChatThreadsView.as_view(), name='community-chat-threads'),
    path('community/my-created/', MyCreatedCommunitiesView.as_view(), name='my-created-communities'),
    path('community/explore/', ExploreCommunitiesView.as_view(), name='explore-communities'),
    path('communities/favorites/', MyFavoriteCommunitiesView.as_view(), name='favorite-communities'),
    path('communities/<int:community_id>/toggle-favorite/', ToggleFavoriteCommunityView.as_view(), name='toggle-favorite'),
    path('users/followers/', MyFollowersView.as_view(), name='my-followers'),
    path('users/chat-eligible-followers/', MyFollowingView.as_view(), name='chat-eligible-followers'),
    path('users/<int:user_id>/follow/', FollowUserView.as_view(), name='follow-user'),
    path('users/<int:user_id>/unfollow/', UnfollowUserView.as_view(), name='unfollow-user'),
    path('communities/<int:community_id>/feed/', CommunityFeedView.as_view(), name='community-feed'),
    path('posts/<int:post_id>/like/', TogglePostLikeView.as_view(), name='post-like-toggle'),
    path('posts/<int:post_id>/comments/', PostCommentListCreateView.as_view(), name='post-comments'),
    path('communities/<int:community_id>/media/photos/', CommunityPhotosView.as_view(), name='community-photos'),
    path('communities/<int:community_id>/media/videos/', CommunityVideosView.as_view(), name='community-videos'),
    path('communities/<int:community_id>/media/documents/', CommunityDocumentsView.as_view(), name='community-documents'),
    path('communities/<int:community_id>/leave/', LeaveCommunityView.as_view(), name='leave-community'),
    path('communities/<int:community_id>/report/', ReportCommunityView.as_view(), name='report-community'),
    path('communities/<int:community_id>/add-member/', AddCommunityMemberView.as_view(), name='add-community-member')
]
